# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       bluez

# >> macros
%define _system_groupadd() getent group %{1} >/dev/null || groupadd -g 1002 %{1}
# << macros

Summary:    Bluetooth utilities
Version:    5.37
Release:    1
Group:      Applications/System
License:    GPLv2+
URL:        http://www.bluez.org/
Source0:    http://www.kernel.org/pub/linux/bluetooth/%{name}-%{version}.tar.gz
Source1:    bluez.tracing
Requires:   bluez-libs = %{version}
Requires:   dbus >= 0.60
Requires:   hwdata >= 0.215
Requires:   bluez-configs
Requires:   systemd
#Requires:   ofono
Requires:   oneshot
Requires(pre): /usr/sbin/groupadd
Requires(preun): systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libusb)
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(udev)
BuildRequires:  pkgconfig(sndfile)
BuildRequires:  pkgconfig(glib-2.0)
#BuildRequires:  pkgconfig(gstreamer-plugins-base-0.10)
#BuildRequires:  pkgconfig(gstreamer-0.10)
BuildRequires:  pkgconfig(check)
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  readline-devel
BuildRequires:  automake
BuildRequires:  autoconf

%description
Utilities for use in Bluetooth applications:
#	--ciptool
#	--dfutool
#	--hcitool
#	--l2ping
#	--rfcomm
#	--sdptool
#	--hciattach
#	--hciconfig
#	--hid2hci

The BLUETOOTH trademarks are owned by Bluetooth SIG, Inc., U.S.A.


%package libs
Summary:    Libraries for use in Bluetooth applications
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
Libraries for use in Bluetooth applications.

%package libs-devel
Summary:    Development libraries for Bluetooth applications
Group:      Development/Libraries
Requires:   bluez-libs = %{version}

%description libs-devel
bluez-libs-devel contains development libraries and headers for
use in Bluetooth applications.


%package cups
Summary:    CUPS printer backend for Bluetooth printers
Group:      System/Daemons
Requires:   %{name} = %{version}-%{release}
Requires:   bluez-libs = %{version}
Requires:   cups

%description cups
This package contains the CUPS backend

#%package alsa
#Summary:    ALSA support for Bluetooth audio devices
#Group:      System/Daemons
#Requires:   %{name} = %{version}-%{release}
#Requires:   bluez-libs = %{version}

#%description alsa
#This package contains ALSA support for Bluetooth audio devices

#%package gstreamer
#Summary:    GStreamer support for SBC audio format
#Group:      System/Daemons
#Requires:   %{name} = %{version}-%{release}
#Requires:   bluez-libs = %{version}

#%description gstreamer
#This package contains gstreamer plugins for the Bluetooth SBC audio format

%package test
Summary:    Test Programs for BlueZ
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires:   bluez-libs = %{version}
Requires:   dbus-python
Requires:   pygobject2 >= 3.10.2

%description test
Scripts for testing BlueZ and its functionality

%package doc
Summary:    Documentation for bluez
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
This package provides man page documentation for bluez

%package configs-mer
Summary:    Default configuration for bluez
Group:      Applications/System
Requires:   %{name} = %{version}-%{release}
Provides:   bluez-configs

%description configs-mer
This package provides default configs for bluez

%package tracing
Summary:    Configuration for bluez to enable tracing
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description tracing
Will enable tracing for BlueZ

%prep
%setup -q -n %{name}-%{version}/%{name}

./bootstrap

%build
autoreconf --force --install

%configure --disable-static \
    --disable-obex \
    --enable-library

make %{?jobs:-j%jobs}


%check
# run unit tests
#make check

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p $RPM_BUILD_ROOT/%{_lib}/systemd/system/network.target.wants
ln -s ../bluetooth.service $RPM_BUILD_ROOT/%{_lib}/systemd/system/network.target.wants/bluetooth.service
(cd $RPM_BUILD_ROOT/%{_lib}/systemd/system && ln -s bluetooth.service dbus-org.bluez.service)

# Remove the cups backend from libdir, and install it in /usr/lib whatever the install
rm -rf ${RPM_BUILD_ROOT}%{_libdir}/cups
#install -D -m 0755 cups/bluetooth ${RPM_BUILD_ROOT}/usr/lib/cups/backend/bluetooth
install -D -m 0755 profiles/cups/bluetooth ${RPM_BUILD_ROOT}/usr/lib/cups/backend/bluetooth

install -d -m 0755 $RPM_BUILD_ROOT%{_localstatedir}/lib/bluetooth

# Install configuration files
for CONFFILE in input network proximity ; do
install -v -m644 profiles/${CONFFILE}/${CONFFILE}.conf ${RPM_BUILD_ROOT}%{_sysconfdir}/bluetooth/${CONFFILE}.conf
done

mkdir -p %{buildroot}%{_sysconfdir}/tracing/bluez/
cp -a %{SOURCE1} %{buildroot}%{_sysconfdir}/tracing/bluez/

# << install post


%pre
%_system_groupadd bluetooth

%preun
if [ "$1" -eq 0 ]; then
systemctl stop bluetooth.service ||:
fi

%post
%{_bindir}/groupadd-user bluetooth
systemctl daemon-reload ||:
systemctl reload-or-try-restart bluetooth.service ||:

%postun
systemctl daemon-reload ||:

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/bccmd
%{_bindir}/bluemoon
%{_bindir}/bluetoothctl
%{_bindir}/btmon
%{_bindir}/ciptool
%{_bindir}/hciattach
%{_bindir}/hciconfig
%{_bindir}/hcidump
%{_bindir}/hcitool
%{_bindir}/hex2hcd
%{_bindir}/l2ping
%{_bindir}/l2test
%{_bindir}/mpris-proxy
%{_bindir}/rctest
%{_bindir}/rfcomm
%{_bindir}/sdptool
%{_libdir}/systemd/user/obex.service
%{_libexecdir}/bluetooth/bluetoothd
%{_libexecdir}/bluetooth/obexd
%{_datadir}/dbus-1/services/org.bluez.obex.service

#%{_bindir}/ciptool
#%{_bindir}/dfutool
#%{_bindir}/dund
#%{_bindir}/gatttool
#%{_bindir}/hcitool
#%{_bindir}/hidd
#%{_bindir}/l2ping
#%{_bindir}/pand
#%{_bindir}/rfcomm
#%{_bindir}/sdptool
#%{_bindir}/mpris-player
#%{_sbindir}/*
%config %{_sysconfdir}/dbus-1/system.d/bluetooth.conf
%{_localstatedir}/lib/bluetooth
/%{_lib}/udev/*
%{_datadir}/dbus-1/system-services/org.bluez.service
/%{_lib}/systemd/system/bluetooth.service
/%{_lib}/systemd/system/network.target.wants/bluetooth.service
/%{_lib}/systemd/system/dbus-org.bluez.service
# << files

%files libs
%defattr(-,root,root,-)
# >> files libs
%{_libdir}/libbluetooth.so.*
%doc AUTHORS COPYING INSTALL README
# << files libs

%files libs-devel
%defattr(-,root,root,-)
# >> files libs-devel
%{_libdir}/libbluetooth.so
%dir %{_includedir}/bluetooth
%{_includedir}/bluetooth/*
%{_libdir}/pkgconfig/bluez.pc
# << files libs-devel

%files cups
%defattr(-,root,root,-)
# >> files cups
%{_libdir}/cups/backend/bluetooth
# << files cups

#%files alsa
#%defattr(-,root,root,-)
# >> files alsa
#%{_libdir}/alsa-lib/*.so
#%{_datadir}/alsa/bluetooth.conf
# << files alsa

#%files gstreamer
#%defattr(-,root,root,-)
# >> files gstreamer
#%{_libdir}/gstreamer-*/*.so
# << files gstreamer

#%files test
#%defattr(-,root,root,-)
# >> files test
#%{_libdir}/%{name}/test/*
#%{_bindir}/hstest
#%{_bindir}/gaptest
#%{_bindir}/sdptest
#%{_bindir}/l2test
#%{_bindir}/btiotest
#%{_bindir}/avtest
#%{_bindir}/bdaddr
#%{_bindir}/scotest
#%{_bindir}/lmptest
#%{_bindir}/attest
#%{_bindir}/agent
#%{_bindir}/test-textfile
#%{_bindir}/rctest
#%{_bindir}/ipctest
#%{_bindir}/uuidtest
# << files test

%files doc
%defattr(-,root,root,-)
# >> files doc
%doc %{_mandir}/man1/*
%doc %{_mandir}/man8/*
# << files doc

%files configs-mer
%defattr(-,root,root,-)
# >> files configs-mer
%config(noreplace) %{_sysconfdir}/bluetooth/*
# << files configs-mer

%files tracing
%defattr(-,root,root,-)
%dir %{_sysconfdir}/tracing/bluez
%config %{_sysconfdir}/tracing/bluez/bluez.tracing
